services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${DB_PORT}:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount current directory for development
      - media_files:/app/media  # Shared media files
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery:
    build: .
    command: celery -A genealogy_extractor worker --loglevel=info
    volumes:
      - .:/app  # Mount current directory for development
      - media_files:/app/media  # Shared media files for processing
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    command: celery -A genealogy_extractor beat --loglevel=info
    volumes:
      - .:/app  # Mount current directory for development
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
  media_files:
