services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: genealogy_extractor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Mount current directory for development
      - media_files:/app/media  # Shared media files
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/genealogy_extractor
      - REDIS_URL=redis://redis:6379/0

  celery:
    build: .
    command: celery -A genealogy_extractor worker --loglevel=info
    volumes:
      - .:/app  # Mount current directory for development
      - media_files:/app/media  # Shared media files for processing
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/genealogy_extractor
      - REDIS_URL=redis://redis:6379/0

  celery-beat:
    build: .
    command: celery -A genealogy_extractor beat --loglevel=info
    volumes:
      - .:/app  # Mount current directory for development
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/genealogy_extractor
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  media_files:
