# Generated by Django 5.2.5 on 2025-08-15 12:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('ocr_completed', models.BooleanField(default=False)),
                ('extraction_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('locality', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'unique_together': {('name', 'locality', 'region', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('maiden_name', models.CharField(blank=True, help_text='Previous surname if changed', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('U', 'Unknown'), ('O', 'Other')], default='U', max_length=1)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_date_estimated', models.BooleanField(default=False)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_date_estimated', models.BooleanField(default=False)),
                ('genealogical_id', models.CharField(blank=True, help_text='e.g., II.1.a', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_documents', models.ManyToManyField(blank=True, related_name='persons', to='genealogy.document')),
                ('birth_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='genealogy.place')),
                ('death_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deaths', to='genealogy.place')),
            ],
            options={
                'ordering': ['surname', 'given_names'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partnership_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('CIVIL_UNION', 'Civil Union'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership'), ('RELATIONSHIP', 'Relationship'), ('OTHER', 'Other')], default='MARRIAGE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_estimated', models.BooleanField(default=False)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_estimated', models.BooleanField(default=False)),
                ('end_reason', models.CharField(blank=True, help_text='divorce, death, separation, etc.', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_documents', models.ManyToManyField(blank=True, related_name='partnerships', to='genealogy.document')),
                ('partners', models.ManyToManyField(related_name='partnerships', to='genealogy.person')),
                ('start_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_starts', to='genealogy.place')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BIRT', 'Birth'), ('DEAT', 'Death'), ('MARR', 'Marriage'), ('DIVR', 'Divorce'), ('BAPT', 'Baptism'), ('BURI', 'Burial'), ('RESI', 'Residence'), ('OCCU', 'Occupation'), ('EDUC', 'Education'), ('IMMI', 'Immigration'), ('EMIG', 'Emigration'), ('OTHER', 'Other')], max_length=5)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_estimated', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_documents', models.ManyToManyField(blank=True, related_name='events', to='genealogy.document')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.partnership')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.person')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='genealogy.place')),
            ],
            options={
                'ordering': ['date', 'event_type'],
            },
        ),
        migrations.CreateModel(
            name='ParentChildRelationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('BIOLOGICAL', 'Biological'), ('ADOPTED', 'Adopted'), ('STEP', 'Step'), ('FOSTER', 'Foster'), ('GUARDIAN', 'Guardian'), ('UNKNOWN', 'Unknown')], default='BIOLOGICAL', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_documents', models.ManyToManyField(blank=True, related_name='parent_child_relationships', to='genealogy.document')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.partnership')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='genealogy.person')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='genealogy.person')),
            ],
            options={
                'unique_together': {('child', 'parent')},
            },
        ),
    ]
