# Generated by Django 5.2.5 on 2025-08-15 13:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0002_remove_document_file_path_remove_document_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='languages',
            field=models.CharField(choices=[('en', 'English'), ('nl', 'Dutch'), ('en+nl', 'English + Dutch')], default='en+nl', help_text='Languages for OCR processing', max_length=10),
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.PositiveIntegerField()),
                ('image_file', models.FileField(upload_to='document_pages/')),
                ('ocr_completed', models.BooleanField(default=False)),
                ('ocr_text', models.TextField(blank=True, help_text='Extracted text from OCR')),
                ('ocr_confidence', models.FloatField(blank=True, help_text='OCR confidence score 0-100', null=True)),
                ('rotation_applied', models.FloatField(default=0.0, help_text='Rotation correction applied in degrees')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='genealogy.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
