# Generated by Django 5.2.5 on 2025-08-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0003_remove_document_file_document_languages_documentpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='languages',
            field=models.CharField(choices=[('eng', 'English'), ('nld', 'Dutch'), ('eng+nld', 'English + Dutch')], default='eng+nld', help_text='Languages for OCR processing', max_length=10),
        ),
    ]
