# Generated by Django 5.2.5 on 2025-08-19 23:38

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0004_alter_document_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text_content', models.TextField(help_text='The actual text content of this chunk')),
                ('chunk_type', models.CharField(choices=[('HEADER', 'Generation Header'), ('CONTENT', 'Genealogy Content'), ('INDEX', 'Index/Reference'), ('OTHER', 'Other')], default='CONTENT', max_length=10)),
                ('start_page', models.PositiveIntegerField(help_text='First page number this chunk appears on')),
                ('end_page', models.PositiveIntegerField(help_text='Last page number this chunk appears on')),
                ('sequence_number', models.PositiveIntegerField(help_text='Order within document')),
                ('generation_number', models.PositiveIntegerField(blank=True, help_text='Generation number (I=1, II=2, etc.)', null=True)),
                ('generation_header', models.CharField(blank=True, help_text='Generation header text if this chunk contains one', max_length=100)),
                ('genealogy_ids', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, help_text="Corrected genealogical IDs found in this chunk (e.g., ['II.1.a', 'II.1.b'])", size=None)),
                ('entities_extracted', models.BooleanField(default=False, help_text='Whether entities have been extracted from this chunk')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_chunks', to='genealogy.document')),
            ],
            options={
                'ordering': ['document', 'sequence_number'],
                'unique_together': {('document', 'sequence_number')},
            },
        ),
    ]
