# Generated by Django 5.2.5 on 2025-08-20 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0005_textchunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='embedding_model_used',
            field=models.CharField(blank=True, help_text='Embedding model used for RAG processing', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='llm_model_used',
            field=models.CharField(blank=True, help_text='LLM model used for entity extraction', max_length=100),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='generation_header',
            field=models.CharField(blank=True, help_text='Generation header text if this chunk contains one', max_length=50),
        ),
    ]
