# Generated by Django 5.2.5 on 2025-08-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0006_document_embedding_model_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='extraction_method',
            field=models.CharField(choices=[('regex', 'Regex patterns'), ('neural_network', 'Neural network (NER)'), ('hybrid', 'Neural network with regex fallback')], default='regex', help_text='Method used to extract genealogical anchors', max_length=20),
        ),
    ]
