# Generated by Django 5.2.5 on 2025-08-23 03:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0007_add_extraction_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='dates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Dates found in this chunk (manually curated)', size=None),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='family_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Family group headers found in this chunk (manually curated)', size=None),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='manually_reviewed',
            field=models.BooleanField(default=False, help_text='Whether this chunk has been manually reviewed and curated'),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='person_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Person names found in this chunk (manually curated)', size=None),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='places',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Places found in this chunk (manually curated)', size=None),
        ),
    ]
