# Generated by Django 5.2.5 on 2025-08-23 13:23

from django.db import migrations, models

import genealogy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0008_textchunk_dates_textchunk_family_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='dates',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Dates found in this chunk (Enter comma-separated values: 15 maart 1654, 22 december 1658)', size=None),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='family_groups',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Family group headers found in this chunk (Enter comma-separated values: II.9. Children of..., III.1. Kinderen van...)', size=None),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='person_names',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Person names found in this chunk (Enter comma-separated values: Johan van der Berg, Maria Janssen)', size=None),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='places',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Places found in this chunk (Enter comma-separated values: Amsterdam, Utrecht, Haarlem)', size=None),
        ),
    ]
