# Generated by Django 5.2.5 on 2025-08-23 14:11

from django.db import migrations, models

import genealogy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0009_alter_textchunk_dates_alter_textchunk_family_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='dates',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Dates found in this chunk (Enter comma-separated ISO dates: 1654-03-15, 1658-12-22)', size=None),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='genealogy_ids',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Corrected genealogical IDs found in this chunk (Enter comma-separated values: II.1.a, II.1.b - Leave empty if none)', size=None),
        ),
    ]
