# Generated by Django 5.2.5 on 2025-09-10 11:50

from django.db import migrations, models

import genealogy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0010_alter_textchunk_dates_alter_textchunk_genealogy_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='family_groups',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Family group headers found in this chunk (Enter comma-separated values: II.9. Children of...)', size=None),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='genealogy_ids',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Corrected genealogical IDs found in this chunk (Enter comma-separated values: II.1.a, II.1.b)', size=None),
        ),
    ]
