# Generated by Django 5.2.5 on 2025-09-12 12:47

import genealogy.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0011_alter_textchunk_family_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='occupations',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Occupations found in this chunk (Enter comma-separated values: metselaar, kuiper, dienstmeid)', size=None),
        ),
    ]
