# Generated by Django 5.2.5 on 2025-09-13 13:10

from django.db import migrations, models

import genealogy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0012_add_occupations_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='source_citations',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, help_text='Source citations (Bronverwijzing) found in this chunk (Enter comma-separated values: RGV SSANO 16.3 Bevolkingsregister Naarden 1850-1862 dl 1 bl 156)', size=None),
        ),
    ]
