# Generated by Django 5.2.5 on 2025-09-13 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0013_add_source_citations_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='related_genealogy_entry',
            field=models.ForeignKey(blank=True, help_text='For narrative chunks: the genealogy entry they provide context for', null=True, on_delete=django.db.models.deletion.CASCADE, to='genealogy.textchunk'),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='chunk_type',
            field=models.CharField(choices=[('HEADER', 'Generation Header'), ('GENEALOGY_ENTRY', 'Dense Biographical Entry'), ('NARRATIVE_CONTEXT', 'Related Context/Story'), ('CONTENT', 'General Genealogy Content'), ('INDEX', 'Index/Reference'), ('OTHER', 'Other')], default='CONTENT', max_length=20),
        ),
    ]
