# Generated by Django 5.2.5 on 2025-09-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0014_add_genealogy_entry_types_and_relationships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='generation_header',
            field=models.CharField(blank=True, help_text='Generation header text if this chunk contains one', max_length=100),
        ),
    ]
