# Generated by Django 5.2.5 on 2025-09-20 18:07

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import pgvector.django.indexes
import pgvector.django.vector
from django.contrib.postgres.operations import CreateExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0015_alter_textchunk_generation_header'),
    ]

    operations = [
        # Create required PostgreSQL extensions before using them
        CreateExtension('vector'),
        CreateExtension('pg_trgm'),

        migrations.AddField(
            model_name='textchunk',
            name='chunk_no',
            field=models.PositiveIntegerField(blank=True, help_text='Sequential chunk number within doc_id', null=True),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='dm_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=list, help_text='Daitch-Mokotoff phonetic codes for surname matching', size=None),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='doc_id',
            field=models.CharField(blank=True, help_text='Document identifier for chunk grouping', max_length=100),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, help_text='Vector embedding for semantic search', null=True),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='textchunk_embedding_ivfflat', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_content'], name='textchunk_content_gin_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['dm_codes'], name='textchunk_dm_codes_gin'),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['person_names'], name='textchunk_person_names_gin'),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['places'], name='textchunk_places_gin'),
        ),
        migrations.AddIndex(
            model_name='textchunk',
            index=models.Index(fields=['doc_id', 'chunk_no'], name='textchunk_doc_chunk_idx'),
        ),
    ]
