# Generated by Django 5.2.5 on 2025-10-04 20:03

from django.db import migrations, models

import genealogy.fields


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0016_add_rag_rrf_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='addresses',
            field=genealogy.fields.CommaSeparatedArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, help_text='Street addresses with house numbers found in this chunk (Enter comma-separated values: Turfpoortstraat 256, Bussumerstraat 146a)', size=None),
        ),
    ]
