# Generated by Django 5.2.5 on 2025-10-04 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0017_textchunk_addresses'),
    ]

    operations = [
    ]
