# Generated by Django 5.2.5 on 2025-10-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0018_change_embedding_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='extracted_people',
            field=models.JSONField(blank=True, default=list, help_text='Structured person data extracted from this chunk: [{"name": "...", "birth_date": "...", "birth_place": "...", "death_date": "...", "genealogy_id": "...", "parents": [...], "spouse": "..."}]'),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='extracted_relationships',
            field=models.JSONField(blank=True, default=list, help_text='Relationship triples extracted from this chunk: [{"person1": "...", "relationship_type": "parent|child|spouse|sibling", "person2": "..."}]'),
        ),
    ]
