# Generated by Django 5.2.5 on 2025-10-08 13:12

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_extracted_people(apps, schema_editor):
    """Convert extracted_people from JSONField to ArrayField"""
    TextChunk = apps.get_model('genealogy', 'TextChunk')
    for chunk in TextChunk.objects.all():
        if chunk.extracted_people_old:
            # Already a list, just copy it
            chunk.extracted_people = chunk.extracted_people_old
            chunk.save(update_fields=['extracted_people'])


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0019_add_structured_extraction_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='textchunk',
            name='textchunk_person_names_gin',
        ),
        migrations.RemoveIndex(
            model_name='textchunk',
            name='textchunk_places_gin',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='genealogy_ids',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='occupations',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='person_names',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='places',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='source_citations',
        ),
        migrations.AddField(
            model_name='textchunk',
            name='extracted_events',
            field=models.JSONField(blank=True, default=list, help_text='Events: [{"person": "...", "event_type": "BIRT|DEAT|MARR|etc", "date": "...", "place": "..."}]'),
        ),
        # Rename old extracted_people field
        migrations.RenameField(
            model_name='textchunk',
            old_name='extracted_people',
            new_name='extracted_people_old',
        ),
        # Create new extracted_people as ArrayField
        migrations.AddField(
            model_name='textchunk',
            name='extracted_people',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), blank=True, default=list, help_text='List of person names extracted from this chunk', size=None),
        ),
        # Copy data
        migrations.RunPython(migrate_extracted_people, migrations.RunPython.noop),
        # Remove old field
        migrations.RemoveField(
            model_name='textchunk',
            name='extracted_people_old',
        ),
        # Update extracted_relationships help text
        migrations.AlterField(
            model_name='textchunk',
            name='extracted_relationships',
            field=models.JSONField(blank=True, default=list, help_text='Relationship triples: [{"person1": "...", "relationship_type": "parent|child|spouse", "person2": "..."}]'),
        ),
    ]
