# Generated by Django 5.2.5 on 2025-10-08 23:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0020_remove_textchunk_textchunk_person_names_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='generation',
            field=models.PositiveIntegerField(blank=True, help_text='Generation number (I=1, II=2, etc.)', null=True),
        ),
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Matching confidence score (0-100). Higher = more likely duplicate')),
                ('match_reasons', models.JSONField(blank=True, default=list, help_text="List of matching signals: ['same_generation', 'same_parents', 'similar_name', etc.]")),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Duplicate - Needs Merge'), ('REJECTED', 'Not a Duplicate'), ('MERGED', 'Already Merged')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_links_from', to='genealogy.person')),
                ('person2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_links_to', to='genealogy.person')),
            ],
            options={
                'ordering': ['-confidence_score', 'review_status'],
                'unique_together': {('person1', 'person2')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='potential_duplicates',
            field=models.ManyToManyField(blank=True, related_name='duplicate_of', through='genealogy.PotentialDuplicate', to='genealogy.person'),
        ),
    ]
