# Generated by Django 5.2.5 on 2025-10-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0021_add_duplicate_detection'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source_chunks',
            field=models.ManyToManyField(blank=True, related_name='persons', to='genealogy.textchunk'),
        ),
    ]
