# Generated by Django 5.2.5 on 2025-10-10 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0022_person_source_chunks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_date_estimated',
        ),
        migrations.RemoveField(
            model_name='person',
            name='birth_place',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_date_estimated',
        ),
        migrations.RemoveField(
            model_name='person',
            name='death_place',
        ),
    ]
