# Generated by Django 5.2.5 on 2025-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0023_remove_person_birth_death_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='chunk_type',
            field=models.CharField(choices=[('HEADER', 'Generation Header'), ('GENEALOGY_ENTRY', 'Dense Biographical Entry'), ('NARRATIVE_CONTEXT', 'Related Context/Story'), ('CONTENT', 'General Genealogy Content'), ('INDEX', 'Index/Reference'), ('KWARTIERSTATEN_HEADER', 'Kwartierstaten Section Header'), ('KWARTIERSTATEN', 'Kwartierstaten Content'), ('APPENDIX_HEADER', 'Appendix/Register Header'), ('APPENDIX', 'Appendix/Register Content'), ('OTHER', 'Other')], default='CONTENT', max_length=30),
        ),
    ]
