# Generated by Django 5.2.5 on 2025-10-18 13:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0024_increase_chunk_type_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='canonical_entity',
            field=models.ForeignKey(blank=True, help_text='The canonical entity this record was merged into (NULL if not merged)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_entities', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='entity_type',
            field=models.CharField(choices=[('EXTRACTED', 'Original Extracted Entity'), ('CANONICAL', 'Merged Canonical Entity')], default='EXTRACTED', help_text='Whether this is an original extraction or a merged canonical entity', max_length=20),
        ),
        migrations.CreateModel(
            name='EntityMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Confidence score for this merge (0-100)')),
                ('merge_algorithm', models.CharField(default='manual', help_text="Algorithm or method used for merge (e.g., 'graph_clustering_v1', 'manual')", max_length=50)),
                ('merge_reason', models.JSONField(blank=True, default=dict, help_text='Detailed merge provenance: matching signals, cluster info, etc.')),
                ('merged_by', models.CharField(default='AUTO', help_text="Who/what performed the merge: username or 'AUTO'", max_length=100)),
                ('merged_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When this merge occurred')),
                ('canonical_entity', models.ForeignKey(help_text='The canonical entity created from merging', on_delete=django.db.models.deletion.CASCADE, related_name='merge_sources', to='genealogy.person')),
                ('source_entity', models.ForeignKey(help_text='The source entity that was merged', on_delete=django.db.models.deletion.CASCADE, related_name='merge_targets', to='genealogy.person')),
            ],
            options={
                'ordering': ['-merged_at'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='merged_from',
            field=models.ManyToManyField(blank=True, help_text='For CANONICAL entities: the source entities that were merged to create this', related_name='merged_into', through='genealogy.EntityMerge', to='genealogy.person'),
        ),
        migrations.AddIndex(
            model_name='entitymerge',
            index=models.Index(fields=['canonical_entity', '-merged_at'], name='genealogy_e_canonic_47f850_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymerge',
            index=models.Index(fields=['source_entity'], name='genealogy_e_source__48eac4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitymerge',
            unique_together={('canonical_entity', 'source_entity')},
        ),
    ]
