# Generated by Django 5.2.5 on 2025-10-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0025_add_entity_merge_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitymerge',
            name='pairwise_similarities',
            field=models.JSONField(blank=True, default=dict, help_text='Dict of {other_source_entity_id: confidence_score} for all pairs in cluster'),
        ),
        migrations.AlterField(
            model_name='entitymerge',
            name='confidence_score',
            field=models.FloatField(help_text='Pairwise confidence score for merging this source into canonical (0-100)'),
        ),
        migrations.AlterField(
            model_name='entitymerge',
            name='merge_reason',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed merge provenance: matching signals, cluster info, atomic similarities, etc.'),
        ),
    ]
