# Generated by Django 5.2.5 on 2025-10-19 13:04

import django.db.models.deletion
import django.utils.timezone
import pgvector.django
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0026_add_pairwise_similarities'),
    ]

    operations = [
        # Remove FK from Event to Person before deleting Person table
        migrations.RemoveField(
            model_name='event',
            name='person',
        ),
        migrations.RemoveField(
            model_name='event',
            name='partnership',
        ),

        # Delete old tables
        migrations.DeleteModel(
            name='EntityMerge',
        ),
        migrations.DeleteModel(
            name='ParentChildRelationship',
        ),
        migrations.DeleteModel(
            name='Partnership',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='PotentialDuplicate',
        ),

        # Create new PersonMention table
        migrations.CreateModel(
            name='PersonMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('given_names', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('maiden_name', models.CharField(blank=True, help_text='Previous surname if changed', max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-binary'), ('U', 'Unknown'), ('O', 'Other')], default='U', max_length=1)),
                ('genealogical_id', models.CharField(blank=True, help_text='e.g., II.1.a', max_length=50)),
                ('generation', models.PositiveIntegerField(blank=True, help_text='Generation number (I=1, II=2, etc.)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunks', models.ManyToManyField(blank=True, related_name='person_mentions', to='genealogy.textchunk')),
                ('source_documents', models.ManyToManyField(blank=True, related_name='person_mentions', to='genealogy.document')),
            ],
            options={
                'db_table': 'genealogy_personmention',
                'ordering': ['surname', 'given_names'],
            },
        ),

        # Create Identity table
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(help_text='Display name for this identity', max_length=500)),
                ('notes', models.TextField(blank=True, help_text='Curator notes about this identity')),
                ('is_deleted', models.BooleanField(default=False, help_text='True if this identity was absorbed into another')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Identities',
                'ordering': ['display_name'],
            },
        ),

        # Create MentionToIdentity mapping table
        migrations.CreateModel(
            name='MentionToIdentity',
            fields=[
                ('mention', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='genealogy.personmention')),
                ('mapped_at', models.DateTimeField(auto_now=True, help_text='When this mapping was last updated')),
                ('mapped_by', models.CharField(default='AUTO', help_text='Who/what updated this mapping', max_length=100)),
                ('identity', models.ForeignKey(help_text='The identity this mention maps to', on_delete=django.db.models.deletion.CASCADE, related_name='mention_mappings', to='genealogy.identity')),
            ],
        ),

        # Create MergeEvent audit log table
        migrations.CreateModel(
            name='MergeEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('merge', 'Merge'), ('unmerge', 'Unmerge'), ('split', 'Split')], max_length=20)),
                ('payload', models.JSONField(help_text='Full transaction details for reversibility')),
                ('performed_by', models.CharField(help_text='User or system that performed this operation', max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('reversed_event', models.ForeignKey(blank=True, help_text='The event this undoes (for unmerge operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='genealogy.mergeevent')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),

        # Create PartnershipMention table FIRST (needed by RelationshipMention FK)
        migrations.CreateModel(
            name='PartnershipMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partnership_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('CIVIL_UNION', 'Civil Union'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership'), ('RELATIONSHIP', 'Relationship'), ('OTHER', 'Other')], default='MARRIAGE', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_date_estimated', models.BooleanField(default=False)),
                ('start_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partnership_starts', to='genealogy.place')),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_date_estimated', models.BooleanField(default=False)),
                ('end_reason', models.CharField(blank=True, help_text='divorce, death, separation, etc.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partners', models.ManyToManyField(related_name='partnerships', to='genealogy.personmention')),
                ('source_documents', models.ManyToManyField(blank=True, related_name='partnerships', to='genealogy.document')),
            ],
            options={
                'db_table': 'genealogy_partnershipmention',
            },
        ),

        # Create RelationshipMention table (after PartnershipMention due to FK)
        migrations.CreateModel(
            name='RelationshipMention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('BIOLOGICAL', 'Biological'), ('ADOPTED', 'Adopted'), ('STEP', 'Step'), ('FOSTER', 'Foster'), ('GUARDIAN', 'Guardian'), ('UNKNOWN', 'Unknown')], default='BIOLOGICAL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='genealogy.personmention')),
                ('parent_mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_relationships', to='genealogy.personmention')),
                ('partnership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='genealogy.partnershipmention')),
                ('source_documents', models.ManyToManyField(blank=True, related_name='parent_child_relationships', to='genealogy.document')),
            ],
            options={
                'db_table': 'genealogy_relationshipmention',
                'unique_together': {('child_mention', 'parent_mention')},
            },
        ),

        # Add new mention and partnership FKs to Event model
        migrations.AddField(
            model_name='event',
            name='mention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.personmention'),
        ),
        migrations.AddField(
            model_name='event',
            name='partnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.partnershipmention'),
        ),

        # Recreate PotentialDuplicate with new FKs
        migrations.CreateModel(
            name='PotentialDuplicate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.FloatField(help_text='Similarity score (0-100)')),
                ('match_reasons', models.JSONField(blank=True, default=list, help_text='List of reasons why these might be duplicates')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Duplicate'), ('REJECTED', 'Not a Duplicate'), ('MERGED', 'Already Merged')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mention1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicates', to='genealogy.personmention')),
                ('mention2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_of', to='genealogy.personmention')),
            ],
            options={
                'ordering': ['-confidence_score', 'review_status'],
                'unique_together': {('mention1', 'mention2')},
            },
        ),

        # Add indexes
        migrations.AddIndex(
            model_name='mentiontoidentity',
            index=models.Index(fields=['identity'], name='genealogy_m_identit_3a3b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeevent',
            index=models.Index(fields=['-performed_at'], name='genealogy_m_perform_8a1c5f_idx'),
        ),
        migrations.AddIndex(
            model_name='mergeevent',
            index=models.Index(fields=['event_type'], name='genealogy_m_event_t_9d4e7a_idx'),
        ),
    ]
