# Generated by Django 5.2.5 on 2025-10-19 13:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0027_create_new_architecture_tables'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mentiontoidentity',
            new_name='genealogy_m_identit_d43d22_idx',
            old_name='genealogy_m_identit_3a3b8e_idx',
        ),
        migrations.RenameIndex(
            model_name='mergeevent',
            new_name='genealogy_m_perform_660c32_idx',
            old_name='genealogy_m_perform_8a1c5f_idx',
        ),
        migrations.RenameIndex(
            model_name='mergeevent',
            new_name='genealogy_m_event_t_7fbf0a_idx',
            old_name='genealogy_m_event_t_9d4e7a_idx',
        ),
        migrations.AddField(
            model_name='personmention',
            name='potential_duplicates',
            field=models.ManyToManyField(blank=True, related_name='duplicate_of', through='genealogy.PotentialDuplicate', to='genealogy.personmention'),
        ),
        migrations.AlterField(
            model_name='identity',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mentiontoidentity',
            name='mention',
            field=models.OneToOneField(help_text='The person mention being mapped', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='genealogy.personmention'),
        ),
        migrations.AlterField(
            model_name='mergeevent',
            name='performed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mergeevent',
            name='performed_by',
            field=models.CharField(default='AUTO', max_length=100),
        ),
        migrations.AlterField(
            model_name='partnershipmention',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='confidence_score',
            field=models.FloatField(help_text='Matching confidence score (0-100). Higher = more likely duplicate'),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='match_reasons',
            field=models.JSONField(blank=True, default=list, help_text="List of matching signals: ['same_generation', 'same_parents', 'similar_name', etc.]"),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='mention1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_links_from', to='genealogy.personmention'),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='mention2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_links_to', to='genealogy.personmention'),
        ),
        migrations.AlterField(
            model_name='potentialduplicate',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('CONFIRMED', 'Confirmed Duplicate - Needs Merge'), ('REJECTED', 'Not a Duplicate'), ('MERGED', 'Already Merged')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='relationshipmention',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
