# Generated by Django 5.2.5 on 2025-10-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0028_rename_genealogy_m_identit_3a3b8e_idx_genealogy_m_identit_d43d22_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personmention',
            name='is_extraction_error',
            field=models.BooleanField(default=False, help_text='Mark true if this mention was incorrectly extracted (not a real person)'),
        ),
    ]
