# Generated by Django 5.2.5 on 2025-11-01 11:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0029_personmention_is_extraction_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Descriptive title for this section (e.g., 'Main Genealogy', 'Index')", max_length=200)),
                ('section_type', models.CharField(choices=[('FRONT_MATTER', 'Front Matter (no processing)'), ('DESCENDANT_GENEALOGY', 'Descendant Genealogy (main processing)'), ('KWARTIERSTATEN', 'Kwartierstaten/Ancestor Tables'), ('APPENDIX_NARRATIVE', 'Appendix Narrative (no processing)'), ('GLOSSARY', 'Glossary (no processing)'), ('INDEX', 'Index (future: 6-column processing)')], help_text='Type of content and processing to apply', max_length=30)),
                ('start_page', models.PositiveIntegerField(help_text='First page number of this section (inclusive)')),
                ('end_page', models.PositiveIntegerField(help_text='Last page number of this section (inclusive)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this section (content description, OCR issues, etc.)')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Display order (auto-set based on start_page if not specified)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(help_text='The document this section belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='book_sections', to='genealogy.document')),
            ],
            options={
                'db_table': 'genealogy_booksection',
                'ordering': ['document', 'sequence', 'start_page'],
                'indexes': [models.Index(fields=['document', 'start_page', 'end_page'], name='genealogy_b_documen_9a2d2a_idx')],
                'unique_together': {('document', 'start_page')},
            },
        ),
    ]
