# Generated by Django 5.2.5 on 2025-11-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0031_alter_textchunk_chunk_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='genealogical_identifier',
            field=models.CharField(blank=True, db_index=True, help_text="Unique genealogical identifier (e.g., 'II.2.a' = generation.family_group.individual_marker)", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='subject',
            field=models.CharField(blank=True, help_text='The primary subject/person of this chunk (for INDIVIDUAL_ENTRY chunks)', max_length=200, null=True),
        ),
    ]
