# Generated by Django 5.2.5 on 2025-11-04 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0032_textchunk_genealogical_identifier_textchunk_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='primary_person_mention',
            field=models.ForeignKey(blank=True, help_text='The PersonMention for the subject of this chunk (only for INDIVIDUAL_ENTRY chunks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_chunks', to='genealogy.personmention'),
        ),
    ]
