# Generated by Django 5.2.5 on 2025-11-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0033_textchunk_primary_person_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personmention',
            name='genealogical_id',
            field=models.CharField(blank=True, help_text='e.g., II.1.a', max_length=50, null=True),
        ),
    ]
