# Generated by Django 5.2.5 on 2025-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0034_alter_personmention_genealogical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='genealogical_identifier',
            field=models.CharField(blank=True, db_index=True, help_text="Unique genealogical identifier (e.g., 'II.2.a' = generation.family_group.individual_marker)", max_length=50, null=True),
        ),
    ]
