# Generated by Django 5.2.5 on 2025-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0035_add_genealogical_identifier_to_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textchunk',
            name='chunk_type',
            field=models.CharField(choices=[('generation_header', 'Generation Header'), ('family_group_header', 'Family Group Header'), ('individual_entry', 'Individual Entry'), ('biographical_text', 'Biographical Text'), ('source_citation', 'Source Citation'), ('narrative_context', 'Narrative Context'), ('info_box', 'Info Box'), ('image', 'Image'), ('image_caption', 'Image Caption'), ('table', 'Table'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
    ]
