# Generated by Django 5.2.5 on 2025-11-11 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0036_update_chunk_types_to_enum_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('BIOLOGICAL', 'Biological'), ('ADOPTED', 'Adopted'), ('STEP', 'Step'), ('FOSTER', 'Foster')], default='BIOLOGICAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='mentiontoidentity',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='mentiontoidentity',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='mergeevent',
            name='reversed_event',
        ),
        migrations.RemoveField(
            model_name='partnershipmention',
            name='partners',
        ),
        migrations.RemoveField(
            model_name='partnershipmention',
            name='source_documents',
        ),
        migrations.RemoveField(
            model_name='partnershipmention',
            name='start_place',
        ),
        migrations.RemoveField(
            model_name='relationshipmention',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='event',
            name='partnership',
        ),
        migrations.RemoveField(
            model_name='personmention',
            name='potential_duplicates',
        ),
        migrations.RemoveField(
            model_name='personmention',
            name='source_chunks',
        ),
        migrations.RemoveField(
            model_name='personmention',
            name='source_documents',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mention',
        ),
        migrations.RemoveField(
            model_name='textchunk',
            name='primary_person_mention',
        ),
        migrations.AlterUniqueTogether(
            name='potentialduplicate',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='relationshipmention',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='relationshipmention',
            name='parent_mention',
        ),
        migrations.RemoveField(
            model_name='potentialduplicate',
            name='mention2',
        ),
        migrations.RemoveField(
            model_name='potentialduplicate',
            name='mention1',
        ),
        migrations.RemoveField(
            model_name='relationshipmention',
            name='child_mention',
        ),
        migrations.RemoveField(
            model_name='relationshipmention',
            name='source_documents',
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['person', 'event_type', 'date']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date_estimated',
        ),
        migrations.RemoveField(
            model_name='event',
            name='source_documents',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='event',
            name='source_chunk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='genealogy.textchunk'),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='entities_persisted',
            field=models.BooleanField(default=False, help_text='Whether Event/Occupation records have been created from extracted JSON'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('BIRTH', 'Birth'), ('DEATH', 'Death'), ('BAPTISM', 'Baptism'), ('MARRIAGE', 'Marriage'), ('OCCUPATION', 'Occupation'), ('RESIDENCE', 'Residence'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='textchunk',
            name='entities_extracted',
            field=models.BooleanField(default=False, help_text='Whether LLM has extracted entities into JSON fields'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('genealogical_id', models.CharField(db_index=True, help_text='Format: II.3.a (generation.family_group.individual)', max_length=50, unique=True)),
                ('given_names', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('generation', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_chunks', models.ManyToManyField(related_name='people', to='genealogy.textchunk')),
                ('source_documents', models.ManyToManyField(related_name='people', to='genealogy.document')),
            ],
            options={
                'ordering': ['genealogical_id'],
            },
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partnership_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership'), ('UNKNOWN', 'Unknown')], default='MARRIAGE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_documents', models.ManyToManyField(related_name='partnerships', to='genealogy.document')),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_partner1', to='genealogy.person')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_as_partner2', to='genealogy.person')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='primary_person',
            field=models.ForeignKey(blank=True, help_text='The Person for the subject of this chunk (only for INDIVIDUAL_ENTRY chunks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_chunks', to='genealogy.person'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['person', 'event_type'], name='genealogy_e_person__5ff453_idx'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_relationships', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_relationships', to='genealogy.person'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='source_documents',
            field=models.ManyToManyField(related_name='relationships', to='genealogy.document'),
        ),
        migrations.DeleteModel(
            name='Identity',
        ),
        migrations.DeleteModel(
            name='MentionToIdentity',
        ),
        migrations.DeleteModel(
            name='MergeEvent',
        ),
        migrations.DeleteModel(
            name='PartnershipMention',
        ),
        migrations.DeleteModel(
            name='PotentialDuplicate',
        ),
        migrations.DeleteModel(
            name='PersonMention',
        ),
        migrations.DeleteModel(
            name='RelationshipMention',
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['genealogical_id'], name='genealogy_p_genealo_fa163a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['surname', 'given_names'], name='genealogy_p_surname_015f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['partner1'], name='genealogy_p_partner_0eb606_idx'),
        ),
        migrations.AddIndex(
            model_name='partnership',
            index=models.Index(fields=['partner2'], name='genealogy_p_partner_2be2f3_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnership',
            constraint=models.CheckConstraint(condition=models.Q(('partner1', models.F('partner2')), _negated=True), name='partners_different'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['parent'], name='genealogy_r_parent__631c10_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['child'], name='genealogy_r_child_i_c14b17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('parent', 'child', 'relationship_type')},
        ),
    ]
