# Generated by Django 5.2.5 on 2025-11-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0037_simplify_to_person_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('BIRTH', 'Birth'), ('BIRT', 'Birth (alt)'), ('DEATH', 'Death'), ('DEAT', 'Death (alt)'), ('BAPT', 'Baptism'), ('BURI', 'Burial'), ('MARR', 'Marriage'), ('DIVR', 'Divorce'), ('OCCU', 'Occupation'), ('RESI', 'Residence'), ('EDUC', 'Education'), ('IMMI', 'Immigration'), ('EMIG', 'Emigration'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
