# Generated by Django 5.2.5 on 2025-11-13 14:01

from django.db import migrations, models


def migrate_dates_forward(apps, schema_editor):
    """Parse existing date strings into DateField"""
    Event = apps.get_model('genealogy', 'Event')

    # Import date parser
    from dateutil import parser as date_parser
    import re
    from datetime import date

    for event in Event.objects.all():
        if event.date_original:
            try:
                # Same logic as parse_genealogical_date
                date_str = event.date_original.strip()

                # Check for approximation
                is_approximate = False
                approx_indicators = ['ca.', 'ca', 'circa', '~', 'about', 'abt', 'est', 'estimated', 'approx']
                for indicator in approx_indicators:
                    if indicator in date_str.lower():
                        is_approximate = True
                        date_str = re.sub(rf'\b{re.escape(indicator)}\b\.?', '', date_str, flags=re.IGNORECASE)
                        date_str = date_str.replace('~', '').strip()

                # Parse
                parsed = date_parser.parse(date_str, fuzzy=True, default=date(1, 1, 1))

                # If just a year
                if re.match(r'^\d{4}$', date_str.strip()):
                    event.date = date(parsed.year, 1, 1)
                else:
                    # parsed might be datetime or date
                    event.date = parsed.date() if hasattr(parsed, 'date') and callable(parsed.date) else parsed
                event.date_approximate = is_approximate
                event.save(update_fields=['date', 'date_approximate'])
            except Exception as e:
                # Leave date as None if unparseable
                print(f"Could not parse date '{event.date_original}' for event {event.id}: {e}")
                pass


def migrate_dates_backward(apps, schema_editor):
    """Copy date back to date_original (best effort)"""
    Event = apps.get_model('genealogy', 'Event')

    for event in Event.objects.all():
        if event.date and not event.date_original:
            event.date_original = event.date.isoformat()
            event.save(update_fields=['date_original'])


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0038_alter_event_event_type'),
    ]

    operations = [
        # Step 1: Add new fields
        migrations.AddField(
            model_name='event',
            name='date_approximate',
            field=models.BooleanField(default=False, help_text='Whether the date is approximate/estimated'),
        ),
        migrations.AddField(
            model_name='event',
            name='date_original',
            field=models.CharField(blank=True, help_text='Original date string from source', max_length=200),
        ),

        # Step 2: Copy existing date (CharField) to date_original
        migrations.RunSQL(
            sql="UPDATE genealogy_event SET date_original = date WHERE date IS NOT NULL AND date != '';",
            reverse_sql="",
        ),

        # Step 3: Drop the old date field and recreate as DateField
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, help_text='Parsed date', null=True),
        ),

        # Step 4: Parse date_original into date
        migrations.RunPython(migrate_dates_forward, migrate_dates_backward),

        # Step 5: Update event_type choices
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('BIRT', 'Birth'), ('DEAT', 'Death'), ('BAPT', 'Baptism'), ('BURI', 'Burial'), ('MARR', 'Marriage'), ('DIVR', 'Divorce'), ('OCCU', 'Occupation'), ('RESI', 'Residence'), ('EDUC', 'Education'), ('IMMI', 'Immigration'), ('EMIG', 'Emigration'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
