# Generated by Django 5.2.5 on 2025-11-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0039_change_event_date_to_datefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_format',
            field=models.CharField(choices=[('DMY', 'Day-Month-Year (European: 15.3.1850)'), ('MDY', 'Month-Day-Year (US: 3/15/1850)')], default='DMY', help_text='Expected date format in this document for parsing ambiguous dates', max_length=3),
        ),
    ]
