# Generated by Django 5.2.5 on 2025-11-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0041_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='search_tier',
            field=models.CharField(choices=[('metadata', 'Metadata Only - No Embedding'), ('narrative', 'Narrative Content - Full Embedding')], db_index=True, default='metadata', help_text='Determines search strategy: metadata uses trigram/phonetic only, narrative uses full embeddings', max_length=20),
        ),
    ]
