# Generated by Django 5.2.5 on 2025-12-06 15:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0042_add_search_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_template_name', models.CharField(help_text="Name of the prompt template used (e.g., 'agent_main_v1')", max_length=100)),
                ('prompt_version', models.CharField(help_text="Version of the prompt template (e.g., '1.2.0')", max_length=20)),
                ('system_prompt', models.TextField(blank=True, help_text='System prompt sent to the LLM')),
                ('user_prompt', models.TextField(help_text='User prompt sent to the LLM')),
                ('full_prompt', models.TextField(help_text='Complete assembled prompt (system + user combined for logging)')),
                ('prompt_variables', models.JSONField(default=dict, help_text='Variables used to render the template')),
                ('model_name', models.CharField(help_text="LLM model used (e.g., 'llama3.1:8b', 'qwen2.5:14b')", max_length=100)),
                ('iteration', models.PositiveIntegerField(default=1, help_text='Iteration number in agent loop (1 = first call)')),
                ('tool_calls', models.JSONField(default=list, help_text='List of tool calls made up to this iteration')),
                ('llm_response', models.TextField(blank=True, help_text='Raw response from the LLM')),
                ('parsed_successfully', models.BooleanField(default=True, help_text='Whether the response was parsed successfully')),
                ('parse_error', models.TextField(blank=True, help_text='Error message if parsing failed')),
                ('latency_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('token_count_prompt', models.IntegerField(blank=True, help_text='Approximate token count of prompt', null=True)),
                ('token_count_response', models.IntegerField(blank=True, help_text='Approximate token count of response', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(help_text='The message this prompt was used to generate', on_delete=django.db.models.deletion.CASCADE, related_name='prompt_logs', to='genealogy.message')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['message', 'iteration'], name='genealogy_p_message_cbea4b_idx'), models.Index(fields=['prompt_template_name', 'prompt_version'], name='genealogy_p_prompt__ff3134_idx'), models.Index(fields=['model_name'], name='genealogy_p_model_n_ad7e24_idx'), models.Index(fields=['created_at'], name='genealogy_p_created_fb5230_idx')],
            },
        ),
    ]
