# Generated by Django 5.2.5 on 2025-12-06 16:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0043_promptlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, help_text="Template name (e.g., 'agent', 'extraction')", max_length=100)),
                ('version', models.CharField(help_text="Version number (e.g., '1', '2', '3')", max_length=20)),
                ('system_template', models.TextField(help_text='System prompt template with {variables}')),
                ('user_template', models.TextField(help_text='User prompt template with {variables}')),
                ('description', models.TextField(blank=True, help_text='What changed in this version')),
                ('created_by', models.CharField(blank=True, help_text='Who created this template', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Is this the active version? (Only one active per name)')),
                ('is_archived', models.BooleanField(default=False, help_text='Archive old experimental versions')),
                ('required_variables', models.JSONField(blank=True, default=list, help_text="List of required variable names (e.g., ['user_query', 'tools_description'])")),
                ('example_variables', models.JSONField(blank=True, default=dict, help_text='Example values for testing template rendering')),
            ],
            options={
                'ordering': ['name', '-version'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='genealogy_p_name_d889ea_idx')],
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='prompt_template_override',
            field=models.ForeignKey(blank=True, help_text='Override active template for this conversation (for A/B testing)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations_using', to='genealogy.prompttemplate'),
        ),
    ]
