# Generated by Django 5.2.5 on 2025-12-06 16:05

from django.db import migrations


def load_agent_v1_template(apps, schema_editor):
    """Load the initial agent v1 prompt template."""
    PromptTemplate = apps.get_model('genealogy', 'PromptTemplate')

    system_prompt = """You are a genealogy research assistant. You use tools iteratively to answer questions about genealogical records.

TOOL FORMAT:
Respond with EXACTLY one of these formats:

TOOL_CALL: <tool_name>
ARGUMENTS: {{"param": "value"}}
REASONING: <why you're calling this>

OR

ANSWER: <your complete response>

CRITICAL RULES:
1. Start responses with "TOOL_CALL:" or "ANSWER:" - no text before these keywords
2. Tools that search by name return "id" or "genealogical_id" fields - extract and use these IDs for subsequent calls
3. If a tool call fails, try a different approach - never repeat the exact same failing call
4. When multiple people match a name, list ALL of them and ask the user to clarify
5. Track conversation context - if user refers to someone mentioned earlier, use that person's ID from previous tool results

ERROR RECOVERY:
- "Person not found: <name>" → You passed a name instead of ID. Search first, extract ID.
- "DUPLICATE CALL BLOCKED" → You already made this exact call. Use the previous result.
- Empty results → The information doesn't exist. Say what you found and what's missing.
"""

    user_prompt = """USER QUERY: {user_query}

AVAILABLE TOOLS:
{tools_description}

PREVIOUS TOOL CALLS ({num_calls}/{max_iterations}):
{previous_calls}

CURRENT CONTEXT:
{context}

Respond with TOOL_CALL or ANSWER:
"""

    PromptTemplate.objects.create(
        name='agent',
        version='1',
        system_template=system_prompt,
        user_template=user_prompt,
        description='Initial agent prompt template migrated from files',
        created_by='system',
        is_active=True,
        is_archived=False,
        required_variables=[
            'user_query',
            'tools_description',
            'num_calls',
            'max_iterations',
            'previous_calls',
            'context'
        ],
        example_variables={
            'user_query': 'Who is Bessel van Zanten?',
            'tools_description': '- search_person_by_name: Search for people by name',
            'num_calls': 0,
            'max_iterations': 20,
            'previous_calls': 'None',
            'context': 'No context yet.'
        }
    )


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0044_prompttemplate_conversation_prompt_template_override'),
    ]

    operations = [
        migrations.RunPython(load_agent_v1_template, reverse_code=migrations.RunPython.noop),
    ]
