# Generated by Django 5.2.5 on 2025-12-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0045_load_initial_prompt_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='textchunk',
            name='text_summary',
            field=models.TextField(blank=True, help_text='LLM-generated summary for chunks over 1000 chars. Used in agent responses to reduce context size.', null=True),
        ),
    ]
