# Generated by Django 5.2.5 on 2026-06-28 13:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0046_add_text_summary_to_textchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abbreviation', models.CharField(db_index=True, help_text='Short code used in citations (e.g. RAR, GAA, NHA)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full archive name', max_length=255)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='Netherlands', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('opening_hours', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
    ]
