# Generated by Django 5.2.5 on 2026-07-05 08:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genealogy', '0047_add_archive_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('toegangsnummer', models.CharField(help_text='Access number', max_length=100)),
                ('inventarisnummer', models.CharField(help_text='Inventory number', max_length=100)),
                ('page_number', models.PositiveIntegerField()),
                ('image_file', models.ImageField(upload_to='source_images/%Y/%m/')),
                ('is_handwritten', models.BooleanField(help_text='Set by the uploading user; determines which pipeline processes this image')),
                ('transcription_method', models.CharField(blank=True, choices=[('loghi', 'Loghi HTR (handwritten)'), ('ollama_deepseek_ocr', 'Ollama DeepSeek-OCR (printed)')], max_length=30)),
                ('transcription_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('raw_transcription', models.TextField(blank=True)),
                ('transcription_error', models.TextField(blank=True)),
                ('transcribed_at', models.DateTimeField(blank=True, null=True)),
                ('translation_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('translation', models.TextField(blank=True)),
                ('translation_model', models.CharField(blank=True, max_length=100)),
                ('translation_error', models.TextField(blank=True)),
                ('translated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_images', to='genealogy.archive')),
                ('persons', models.ManyToManyField(related_name='source_images', to='genealogy.person')),
            ],
            options={
                'ordering': ['archive', 'toegangsnummer', 'inventarisnummer', 'page_number'],
                'indexes': [models.Index(fields=['archive', 'toegangsnummer', 'inventarisnummer'], name='genealogy_s_archive_58c838_idx')],
            },
        ),
    ]
